// React/src/Demo10/Product.jsx
const Product = (props) => {
  const AlreadyAdded =
    props.selectedProducts &&
    props.selectedProducts.find((existingId) => {
      return existingId === props.Id;
    });
  const handleCard = () => {
    if (AlreadyAdded) {
      const listWithoutThisProduct = props.selectedProducts.filter(
        (productID) => {
          return productID !== props.Id;
        }
      );
      props.setSelectedProducts(listWithoutThisProduct);
    } else {
      props.setSelectedProducts([...props.selectedProducts, props.Id]);
    }
  };
  return (
    <>
      <div className="card mx-4 my-4" style={{ maxWidth: "18rem" }}>
        <img
          className="card-img-top"
          style={{ width: "100%", height: 230 }}
          src={props.Image}
          alt={props.Name}
        />
        <div className="card-body">
          <div className="d-flex  justify-content-between align-items-center ">
            <h5 className="card-title">{props.Name}</h5>
            <p className="text-success fw-bold">{props.Likes} jaime</p>
          </div>
          {props.showTextAndBtn && <p className="card-text">{props.Comment}</p>}
          {props.Discount > 0 ? (
            <div>
              <span className="text-decoration-line-through">
                {props.Price}$
              </span>
              <span className="text-danger m-2">
                {(props.Price * props.Discount) / 100}$
              </span>
            </div>
          ) : (
            <span>{props.Price}$</span>
          )}
        </div>
        <div className="d-flex m-2 justify-content-between align-items-center">
          {props.showTextAndBtn && (
            <button
              onClick={handleCard}
              className={`btn  ${AlreadyAdded ? "btn-danger" : "btn-primary"}`}
            >
              {AlreadyAdded ? "remove from" : "add to card"}
            </button>
          )}
        </div>
      </div>
    </>
  );
};

export default Product;

// Angular/Demo5/src/app/product/product.component.ts
import { Component, Input } from '@angular/core';
import { Product } from 'src/models/product';
@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})

export class ProductComponent {
  
get message () {
 return this.product.LikeCount > 10 ? "Offers star" : ""; 
}

@Input() product:Product = {Id: 0,Name : "",Image : "", Comment :"",Price : 0, Discount:0, LikeCount:0}
 
}

<div class="card">
    <img class="card-img-top" src="{{product.Image}}" alt="Card image cap"/>
<!--
    <div class="d-flex flex-row justify-content-center text-warning">
        {{message}}
    </div>
-->
    <div class="card-body">
        <h5 class="card-title">{{product.Name}}
            <label  class="float-end">{{product.LikeCount}}</label>
        </h5>
        <p class="card-text">{{product.Comment}}</p>
     <div *ngIf="product.Discount > 0; else Divdiscount">
           <span class="text-decoration-line-through">{{product.Price}}€</span>
        <span class="text-danger m-2">{{product.Price * product.Discount / 100}}€</span>
    </div>
    </div>
    <div class="card-footer">
        <div class="btn-ground text-center pb-1">
            <button type="button" class="btn btn-primary m-2"><i class="fa fa-shopping-cart"></i>Ajouter au panier</button>
            <button type="button" class="btn btn-primary" (click)="product.LikeCount = product.LikeCount + 1"><i class="fa fa-info"></i> J'aime</button>
        </div>
    </div>
</div>
<div> <ng-template #Divdiscount><span>{{product.Price}}€</span></ng-template>   </div>
