// Angular/Demo5/src/app/product/product.component.ts
import { Component, Input } from '@angular/core';
import { Product } from 'src/models/product';
@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})

export class ProductComponent {
  
get message () {
 return this.product.LikeCount > 10 ? "Offers star" : ""; 
}

@Input() product:Product = {Id: 0,Name : "",Image : "", Comment :"",Price : 0, Discount:0, LikeCount:0}
 
}

<div class="card">
    <img class="card-img-top" src="{{product.Image}}" alt="Card image cap"/>
<!--
    <div class="d-flex flex-row justify-content-center text-warning">
        {{message}}
    </div>
-->
    <div class="card-body">
        <h5 class="card-title">{{product.Name}}
            <label  class="float-end">{{product.LikeCount}}</label>
        </h5>
        <p class="card-text">{{product.Comment}}</p>
     <div *ngIf="product.Discount > 0; else Divdiscount">
           <span class="text-decoration-line-through">{{product.Price}}€</span>
        <span class="text-danger m-2">{{product.Price * product.Discount / 100}}€</span>
    </div>
    </div>
    <div class="card-footer">
        <div class="btn-ground text-center pb-1">
            <button type="button" class="btn btn-primary m-2"><i class="fa fa-shopping-cart"></i>Ajouter au panier</button>
            <button type="button" class="btn btn-primary" (click)="product.LikeCount = product.LikeCount + 1"><i class="fa fa-info"></i> J'aime</button>
        </div>
    </div>
</div>
<div> <ng-template #Divdiscount><span>{{product.Price}}€</span></ng-template>   </div>

// React/src/Demo6/Product.jsx
import filledHeart from "../assets/heart_filled.png";
import heartEmpty from "../assets/heart_empty.png";
import { useState } from "react";

const Product = ({ Name, Image, Price, Comment, Discount, Likes } = props) => {
  const [isLiked, setIsLiked] = useState(false);
  const handleLike = () => {
    setIsLiked((c) => !c);
  };
  return (
    <>
      <div className="card mx-4 my-4" style={{ maxWidth: "18rem" }}>
        <img
          className="card-img-top"
          style={{ width: "100%", height: 230 }}
          src={Image}
          alt={Name}
        />
        <div className="card-body">
          <div className="d-flex  justify-content-between align-items-center ">
            <h5 className="card-title">{Name}</h5>
            <p className="text-success fw-bold">
              {isLiked ? Likes + 1 : Likes} jaime
            </p>
          </div>
          <p className="card-text">{Comment}</p>
          {Discount > 0 ? (
            <div>
              <span className="text-decoration-line-through">{Price}$</span>
              <span className="text-danger m-2">
                {(Price * Discount) / 100}$
              </span>
            </div>
          ) : (
            <span>{Price}$</span>
          )}
        </div>
        <div className="d-flex m-2 justify-content-between align-items-center">
          <button className=" btn btn-primary">Ajouter au panier</button>
          <img
            onClick={handleLike}
            src={isLiked ? filledHeart : heartEmpty}
            style={{ width: 25, height: 25, cursor: "pointer" }}
          />
        </div>
      </div>
    </>
  );
};

export default Product;
