// Angular/Demo4/src/src/app/Components/product/product.component.ts
import { Component, Input } from '@angular/core';
import { Product } from 'src/src/models/product';
@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})

export class ProductComponent {

  public valueLikes : number = 0;

constructor() {}

@Input() product = {Id: 0,Name : "",Image : "", Comment :"",Price : 0, Discount:0}

ngOnInit() {}

IncrementLikes(){
  this.valueLikes++;
}
  
}

<div class="card">
    <img class="card-img-top" src="{{product.Image}}" alt="Card image cap"/>
    <div class="card-body">
        <h5 class="card-title">{{product.Name}}
            <label  class="float-end">{{valueLikes}}</label>
        </h5>
        <p class="card-text">{{product.Comment}}</p>
     <div *ngIf="product.Discount > 0; else Divdiscount">
           <span class="text-decoration-line-through">{{product.Price}}€</span>
        <span class="text-danger m-2">{{product.Price * product.Discount / 100}}€</span>
    </div>
    <div class="row">
        <div class="col-md-12 text-right">
            <button type="button" class="btn btn-primary">Ajouter au panier</button>
            <div class="float-end">
            <button type="button" class="btn btn-warning" (click)="product.valueLikes++;"></button>
        </div>

        </div>
    </div>
    </div>
</div>
    <div>   
    <ng-template #Divdiscount>
     <span>{{product.Price}}€</span>
      </ng-template>   
    </div>

// React/src/Demo5/Product.jsx
const Product = (props) => {
  return (
    <>
      <div className="card mx-4 my-4" style={{ maxWidth: "18rem" }}>
        <img
          className="card-img-top"
          style={{ width: "100%", height: 230 }}
          src={props.Image}
          alt={props.Name}
        />
        <div className="card-body">
          <h5 className="card-title">{props.Name}</h5>
          <p className="card-text">{props.Comment}</p>
          {props.Discount > 0 ? (
            <div>
              <span className="text-decoration-line-through">{props.Price}$</span>
              <span className="text-danger m-2">
                {(props.Price * props.Discount) / 100}$
              </span>
            </div>
          ) : (
            <span>{props.Price}$</span>
          )}
        </div>
      </div>
    </>
  );
};

export default Product;
