// Angular/Demo2/src/app/Components/Product/product/product.component.ts
import { Component } from '@angular/core';
import { Product } from 'src/models/product';

@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})
export class ProductComponent {

  pro : Product = {
    Id:1,
    Name : "Card title",
    Image : "Product1.png",
    Comment : `Some quick example text to build on the card title
               and make up the bulk of the card's content.`,
    Price : 109.99
    }

  constructor() {}

  ngOnInit() {}
  
}

<div class="card myclass" style="width: 18rem;">
    <img class="card-img-top" src="/assets/images/{{pro.Image}}" alt="Card image cap"/>
    <div class="card-body">
        <h5 class="card-title">{{pro.Name}}</h5>
        <p class="card-text">{{pro.Comment}}</p>
        <span>{{pro.Price}}€</span>
    </div>
</div>

// React/src/Demo5/Product.jsx
const Product = (props) => {
  return (
    <>
      <div className="card mx-4 my-4" style={{ maxWidth: "18rem" }}>
        <img
          className="card-img-top"
          style={{ width: "100%", height: 230 }}
          src={props.Image}
          alt={props.Name}
        />
        <div className="card-body">
          <h5 className="card-title">{props.Name}</h5>
          <p className="card-text">{props.Comment}</p>
          {props.Discount > 0 ? (
            <div>
              <span className="text-decoration-line-through">{props.Price}$</span>
              <span className="text-danger m-2">
                {(props.Price * props.Discount) / 100}$
              </span>
            </div>
          ) : (
            <span>{props.Price}$</span>
          )}
        </div>
      </div>
    </>
  );
};

export default Product;
