// React/src/Demo5/Product.jsx
const Product = (props) => {
  return (
    <>
      <div className="card mx-4 my-4" style={{ maxWidth: "18rem" }}>
        <img
          className="card-img-top"
          style={{ width: "100%", height: 230 }}
          src={props.Image}
          alt={props.Name}
        />
        <div className="card-body">
          <h5 className="card-title">{props.Name}</h5>
          <p className="card-text">{props.Comment}</p>
          {props.Discount > 0 ? (
            <div>
              <span className="text-decoration-line-through">{props.Price}$</span>
              <span className="text-danger m-2">
                {(props.Price * props.Discount) / 100}$
              </span>
            </div>
          ) : (
            <span>{props.Price}$</span>
          )}
        </div>
      </div>
    </>
  );
};

export default Product;

// Angular/Demo3/src/src/app/Components/product/product.component.ts
import { Component, Input } from '@angular/core';
import { Product } from 'src/src/models/product';
@Component({
  selector: 'app-product',
  templateUrl: './product.component.html',
  styleUrls: ['./product.component.css']
})

export class ProductComponent {

  /*  pro : Product = {
    Id:1,
    Name : "Card title",
    Image : "Product1.png",
    Comment : `Some quick example text to build on the card title
               and make up the bulk of the card's content.`,
    Price : 109.99,
    Discount:50
    }*/

constructor() {}
@Input() product = {Id: 0,Name : "",Image : "", Comment :"",Price : 0, Discount:0}
ngOnInit() {}
  
}

<div class="card">
    <img class="card-img-top" src="{{pro.Image}}" alt="Card image cap"/>
    <div class="card-body">
        <h5 class="card-title">{{pro.Name}}</h5>
        <p class="card-text">{{pro.Comment}}</p>
     
        <div *ngIf="pro.Discount > 0; else Divdiscount">
           <span class="text-decoration-line-through">{{pro.Price}}€</span>
           <span class="text-danger m-2">{{pro.Price * pro.Discount / 100}}€</span>
        </div>
    <div>
    <ng-template #Divdiscount><span>{{pro.Price}}€</span></ng-template>
</div>
